"""Rename search_history.search_at → searched_at

Revision ID: cddde664ee49
Revises: 2a26550b39e4
Create Date: 2025-05-26 17:49:27.121085

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cddde664ee49"
down_revision: Union[str, None] = "2a26550b39e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_history_city_name"), table_name="search_history")
    op.drop_index(op.f("ix_search_history_user_id"), table_name="search_history")
    op.drop_table("search_history")
    op.drop_index(op.f("ix_users_cookie_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('users_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "cookie_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint(
            "cookie_id",
            name="users_cookie_id_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("ix_users_cookie_id"), "users", ["cookie_id"], unique=True)
    op.create_table(
        "search_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("city_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "searched_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("search_history_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("search_history_pkey")),
    )
    op.create_index(
        op.f("ix_search_history_user_id"), "search_history", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_history_city_name"),
        "search_history",
        ["city_name"],
        unique=False,
    )
    # ### end Alembic commands ###
